import yaml

with open('example.yaml', 'r') as file:
    data = yaml.safe_load(file)

print("from mininet.topo import Topo\n")
print("class MyTopo(Topo):")
print("    \"Topology generated by yaml file.\"")
print("    def __init__(self):")
print("        \"Create custom topo.\"")
print("        # Initialize topology")
print("        Topo.__init__( self )")
print("        # Add hosts and switches")

host_num=0
switch_num=0
for node in data['nodes']:
    #print(node['name'], node['vendor'], node['config']['image'], node['interfaces'])
    if node['vendor']=="HOST":
        print("        %s=self.addHost('%s')" % (node['name'], node['name']))
        host_num+=1
    else:
        print("        %s=self.addSwitch('%s')" % (node['name'], node['name']))
        switch_num+=1

print("        # Add links")

for link in data['links']:
     print("        self.addLink(%s,%s)" % (link['a_node'], link['z_node']))
#    print(link)

print("topos = { 'mytopo': ( lambda: MyTopo() ) }")

# print(data)
