#!/bin/bash
# Script generated by process_flows_v2.py to simulate aggregated network traffic using iperf3.
# Mapping file used: ip_mapping_example.csv
# NOTE: The throughput is used as the bandwidth limit (-b) and is assumed to be in Kbps (K).

pkill iperf3 # Clean up any previous iperf3 server daemons before starting

# --- Flow 1: host-A-core -> 10.0.0.102 (UDP) @ 2048K on Port 52905 ---
iperf3 -s -p 52905 -D & # Server on 10.0.0.102
iperf3 -c 10.0.0.102 -p 52905 -u -b 2048K -t 10 # Client from host-A-core
sleep 1

# --- Flow 2: host-A-core -> host-F-router (VRRP) @ 2560K on Port 18296 ---
iperf3 -s -p 18296 -D & # Server on host-F-router
iperf3 -c host-F-router -p 18296 -b 2560K -t 10 # Client from host-A-core
sleep 1

# --- Flow 3: host-D-server -> host-C-fw (GTP) @ 304128K on Port 12639 ---
iperf3 -s -p 12639 -D & # Server on host-C-fw
iperf3 -c host-C-fw -p 12639 -b 304128K -t 10 # Client from host-D-server
sleep 1

# --- Flow 4: host-B-edge -> host-C-fw (SCTP) @ 1176K on Port 59598 ---
iperf3 -s -p 59598 -D & # Server on host-C-fw
iperf3 -c host-C-fw -p 59598 -b 1176K -t 10 # Client from host-B-edge
sleep 1

# --- Flow 5: host-C-fw -> host-B-edge (SCTP) @ 1176K on Port 29024 ---
iperf3 -s -p 29024 -D & # Server on host-B-edge
iperf3 -c host-B-edge -p 29024 -b 1176K -t 10 # Client from host-C-fw
sleep 1

# --- Flow 6: host-C-fw -> 10.252.249.3 (GTP) @ 304744K on Port 27049 ---
iperf3 -s -p 27049 -D & # Server on 10.252.249.3
iperf3 -c 10.252.249.3 -p 27049 -b 304744K -t 10 # Client from host-C-fw
sleep 1

# --- Flow 7: host-E-client -> 10.0.0.255 (UDP) @ 616K on Port 25628 ---
iperf3 -s -p 25628 -D & # Server on 10.0.0.255
iperf3 -c 10.0.0.255 -p 25628 -u -b 616K -t 10 # Client from host-E-client
sleep 1

# --- Flow 8: host-E-client -> 10.0.1.1 (UDP) @ 616K on Port 20144 ---
iperf3 -s -p 20144 -D & # Server on 10.0.1.1
iperf3 -c 10.0.1.1 -p 20144 -u -b 616K -t 10 # Client from host-E-client
sleep 1

# Final cleanup
pkill iperf3
