import pandas as pd
import argparse
import random
import sys
import os

def process_flows(input_csv_file):
    """
    Aggregates flow data, applies IP mapping, and generates a Bash script for iperf3.
    """
    try:
        # Check if the file exists and is readable
        if not os.path.exists(input_csv_file):
            raise FileNotFoundError(f"Input file '{input_csv_file}' not found.")
        
        # Load the CSV file
        df = pd.read_csv(input_csv_file)
    except Exception as e:
        print(f"Error processing file: {e}", file=sys.stderr)
        return

    # --- 1. Aggregate lines by ipsrc, ipdst, and protocol, summing throughput ---
    print("Step 1: Aggregating flows...")
    aggregated_df = df.groupby(['ipsrc', 'ipdst', 'protocol'])['throughput'].sum().reset_index()

    # --- 2. Define and apply IP mapping (Lookup Table) ---
    # NOTE: This is a placeholder lookup table to demonstrate the feature.
    # Replace these with your actual hostnames/aliases if needed.
    ip_lookup_table = {
        '10.252.0.2': 'host_A',
        '10.252.249.2': 'host_B',
        '10.252.40.101': 'host_C',
        '10.252.249.1': 'host_D',
        '10.90.0.1': 'host_E'
        # Any IP not listed here will use its original value.
    }

    def apply_ip_mapping(ip, mapping):
        return mapping.get(ip, ip)

    aggregated_df['ipsrc_mapped'] = aggregated_df['ipsrc'].apply(lambda x: apply_ip_mapping(x, ip_lookup_table))
    aggregated_df['ipdst_mapped'] = aggregated_df['ipdst'].apply(lambda x: apply_ip_mapping(x, ip_lookup_table))
    print(f"Step 2: Applied IP mapping (using {len(ip_lookup_table)} entries).")

    # --- 3. Generate a shell script in bash ---
    shell_script_lines = [
        "#!/bin/bash",
        "#",
        "# Script generated by process_flows.py to simulate aggregated network traffic using iperf3.",
        "# NOTE 1: This script assumes iperf3 is installed on the hosts.",
        "# NOTE 2: The 'server' command (iperf3 -s -D) should run on the DESTINATION host.",
        "# NOTE 3: The 'client' command (iperf3 -c) should run on the SOURCE host.",
        "# NOTE 4: Throughput is used as the bandwidth limit (-b) and is assumed to be in KILOBITS per second (K).",
        "",
        "# Clean up any previous iperf3 server daemons before starting:",
        "pkill iperf3",
        ""
    ]

    # Use a safe, random port range
    PORT_MIN = 11000
    PORT_MAX = 60000
    random.seed(42) # Set seed for predictable port numbers in this run

    for index, row in aggregated_df.iterrows():
        ip_src_mapped = row['ipsrc_mapped']
        ip_dst_mapped = row['ipdst_mapped']
        protocol = row['protocol']
        # The throughput is the sum of all matching flows
        throughput = int(row['throughput'])
        
        # Generate a random port for this flow
        iperf_port = random.randint(PORT_MIN, PORT_MAX)

        # The throughput value is used directly with 'K' suffix (Kilobits/sec)
        throughput_str = f"{throughput}K"
        
        comment = f"# --- Flow {index+1}: {ip_src_mapped} -> {ip_dst_mapped} ({protocol}) @ {throughput_str} on Port {iperf_port} ---"
        shell_script_lines.append(comment)

        # 1. Server command: run on $ip_dst_mapped machine, listening on $iperf_port
        # We use -D to run as a daemon (background process)
        server_cmd = f"# Run on {ip_dst_mapped}: iperf3 -s -p {iperf_port} -D"
        shell_script_lines.append(server_cmd)

        # 2. Client command: run on $ip_src_mapped machine, connecting to $ip_dst_mapped
        if protocol == 'UDP':
            # UDP requires -u, a bandwidth limit (-b), and a time limit (-t)
            client_cmd = f"# Run on {ip_src_mapped}: iperf3 -c {ip_dst_mapped} -p {iperf_port} -u -b {throughput_str} -t 10"
        else:
            # TCP (default for iperf3). -b is bandwidth ceiling, -t 10 is time limit
            client_cmd = f"# Run on {ip_src_mapped}: iperf3 -c {ip_dst_mapped} -p {iperf_port} -b {throughput_str} -t 10"
        
        shell_script_lines.append(client_cmd)
        
        # Add a sleep to wait for the previous flow to finish its 10s run (if applicable)
        shell_script_lines.append("sleep 1") 
        shell_script_lines.append("")

    # Add a final cleanup command
    shell_script_lines.append("# Final cleanup")
    shell_script_lines.append("pkill iperf3")
    shell_script_lines.append("")


    # --- 4. Save the shell file as "run_DT_flows.sh" ---
    output_filename = "run_DT_flows.sh"
    with open(output_filename, 'w') as f:
        f.write('\n'.join(shell_script_lines))
    
    # Make the script executable
    os.chmod(output_filename, 0o755)

    print(f"Step 3 & 4: Successfully generated and saved '{output_filename}'.")
    print("\n\n*** Aggregated Flows ***")
    print(aggregated_df[['ipsrc_mapped', 'ipdst_mapped', 'protocol', 'throughput']].to_markdown(index=False))
    print("\n\nDone! Execute the script from your command line.")
    return

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Aggregate network flow data and generate a Bash script for iperf3 traffic simulation."
    )
    # The command line input should be the CSV file
    parser.add_argument(
        "input_file", 
        type=str, 
        help="The path to the input CSV file containing flow data."
    )
    args = parser.parse_args()
    process_flows(args.input_file)
