import pandas as pd
import argparse
import random
import sys
import os

def load_ip_mapping(mapping_file_path):
    """
    Reads a two-column CSV file (e.g., original_ip,mapped_alias) into a dictionary.
    Returns an empty dictionary if the file is not found or not provided.
    """
    if not mapping_file_path or not os.path.exists(mapping_file_path):
        return {}
    
    try:
        # Assuming the mapping file is a two-column CSV without a header
        mapping_df = pd.read_csv(mapping_file_path, header=None, names=['original_ip', 'mapped_alias'])
        # Clean up potential whitespace
        mapping_df['original_ip'] = mapping_df['original_ip'].astype(str).str.strip()
        mapping_df['mapped_alias'] = mapping_df['mapped_alias'].astype(str).str.strip()
        
        # Convert to dictionary (first column is key, second is value)
        ip_lookup_table = mapping_df.set_index('original_ip')['mapped_alias'].to_dict()
        print(f"Loaded {len(ip_lookup_table)} IP mappings from '{mapping_file_path}'.")
        return ip_lookup_table
    except Exception as e:
        print(f"Warning: Could not read mapping file '{mapping_file_path}'. Using no mapping. Error: {e}", file=sys.stderr)
        return {}

def process_flows(input_csv_file, mapping_file_path=None):
    """
    Aggregates flow data, applies IP mapping from a file, and generates a Bash script for iperf3.
    """
    try:
        df = pd.read_csv(input_csv_file)
    except Exception as e:
        print(f"Error reading flow CSV file: {e}", file=sys.stderr)
        return

    # Load IP mapping
    ip_lookup_table = load_ip_mapping(mapping_file_path)

    # --- 1. Aggregate lines by ipsrc, ipdst, and protocol, summing throughput ---
    print("Step 1: Aggregating flows...")
    aggregated_df = df.groupby(['ipsrc', 'ipdst', 'protocol'])['throughput'].sum().reset_index()

    # --- 2. Apply IP mapping ---
    def apply_ip_mapping(ip, mapping):
        # Use the mapped value if it exists, otherwise use the original IP
        return mapping.get(ip, ip)

    aggregated_df['ipsrc_mapped'] = aggregated_df['ipsrc'].apply(lambda x: apply_ip_mapping(x, ip_lookup_table))
    aggregated_df['ipdst_mapped'] = aggregated_df['ipdst'].apply(lambda x: apply_ip_mapping(x, ip_lookup_table))
    print(f"Step 2: Applied IP mapping (using {len(ip_lookup_table)} entries).")

    # --- 3. Generate a shell script in bash ---
    shell_script_lines = [
        "#!/bin/bash",
        "# Script generated by process_flows_v3.py to simulate aggregated network traffic using iperf3.",
        f"# Mapping file used: {mapping_file_path if mapping_file_path else 'None'}",
        "# NOTE: The throughput is used as the bandwidth limit (-b) and is assumed to be in Kbps (K).",
        "",
        "# Clean up any previous iperf3 server daemons before starting",
        "../../cmd_container.sh internet_server \"pkill iperf3\" ",
        "../../cmd_container.sh ue1 \"pkill iperf3\" ",
	"# Run tcpdump on all interfaces (120 sec.)",
	"sudo tcpdump -i s3-internet -s 0 -G 120 -w all_traffic_internet.pcap &",
        ""
    ]

    PORT_MIN = 11000
    PORT_MAX = 60000
    # Set seed for repeatable random ports (optional)
    random.seed(42) 

    for index, row in aggregated_df.iterrows():
        ip_src_mapped = row['ipsrc_mapped']
        ip_dst_mapped = row['ipdst_mapped']
        protocol = row['protocol']
        throughput = int(row['throughput'])
        
        iperf_port = random.randint(PORT_MIN, PORT_MAX)
        throughput_str = f"{throughput}K"
        
        comment = f"# --- Flow {index+1}: {ip_src_mapped} -> {ip_dst_mapped} ({protocol}) @ {throughput_str} on Port {iperf_port} ---"
        shell_script_lines.append(comment)

        # 1. Server command (Destination host)
        server_cmd = f"../../cmd_container.sh internet_server \"timeout 2m iperf3 -s -B 192.168.0.201 -p {iperf_port} -D\" > output.log 2>&1 &"
        shell_script_lines.append(server_cmd)

        # 2. Client command (Source host)
        if protocol == 'UDP':
            client_cmd = f"../../cmd_container.sh ue1 \"iperf3 -B 10.45.0.4 -c {ip_dst_mapped} -p {iperf_port} -u -b {throughput_str} -t 120\" > output.log 2>&1 &"
        else:
            client_cmd = f"../../cmd_container.sh ue1 \"iperf3 -B 10.45.0.4 -c {ip_dst_mapped} -p {iperf_port} -b {throughput_str} -t 120\" > output.log 2>&1 &"
        
        shell_script_lines.append(client_cmd)
        
        # shell_script_lines.append("sleep 1") 
        shell_script_lines.append("")

    #shell_script_lines.append("# Final cleanup")
    #shell_script_lines.append("../../cmd_container.sh internet_server \"pkill iperf3\" ")
    shell_script_lines.append("")

    # --- 4. Save the shell file as "run_DT_flows.sh" ---
    output_filename = "run_DT_flows.sh"
    with open(output_filename, 'w') as f:
        f.write('\n'.join(shell_script_lines))
    
    os.chmod(output_filename, 0o755)

    print(f"Step 3 & 4: Successfully generated and saved '{output_filename}'.")
    print(aggregated_df[['ipsrc_mapped', 'ipdst_mapped', 'protocol', 'throughput']].to_markdown(index=False))
    print("\n\nDone! Execute the script from your command line.")
    return

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Aggregate network flow data and generate a Bash script for iperf3 traffic simulation."
    )
    parser.add_argument(
        "input_file", 
        type=str, 
        help="The path to the input CSV file containing flow data."
    )
    parser.add_argument(
        "--map-file", 
        type=str, 
        default=None,
        help="Optional: The path to a CSV file containing IP mappings (format: original_ip,mapped_alias)."
    )
    args = parser.parse_args()
    process_flows(args.input_file, args.map_file)
