#!/bin/bash
# Script generated by process_flows_v4.py to simulate aggregated network traffic using iperf3.
# Mapping file used: ip_mapping_cnit.csv
# NOTE: The throughput is used as the bandwidth limit (-b) and is assumed to be in Kbps (K).

# Clean up any previous iperf3 server daemons before starting
../../cmd_container.sh internet_server "pkill iperf3" 
../../cmd_container.sh ue1 "pkill iperf3" 
# Run tcpdump on all interfaces (120 sec.)
#../../cmd_container.sh upf_cld tcpdump -i ogstun -s 0 -G 120 -w capture.pcap &

# --- Flow 1: 1.1.1.1 -> 10.45.202.100 (DNS) @ 1086K on Port 52905 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 52905 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 52905 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.202.100 -p 52905 -b 1086K -t 120" > output.log 2>&1 &

# --- Flow 2: 10.201.1.1 -> 10.45.202.100 (DTLSv1.2) @ 1240126K on Port 18296 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 18296 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 18296 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.202.100 -p 18296 -b 1240126K -t 120" > output.log 2>&1 &

# --- Flow 3: 10.201.1.1 -> 10.45.202.100 (STUN) @ 11808K on Port 12639 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 12639 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 12639 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.202.100 -p 12639 -b 11808K -t 120" > output.log 2>&1 &

# --- Flow 4: 10.201.1.1 -> 10.45.202.100 (UDP) @ 39513120K on Port 59598 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 59598 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 59598 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -u -B 10.45.0.4 -c 10.45.202.100 -p 59598 -u -b 39513120K -t 120" > output.log 2>&1 &

# --- Flow 5: 10.45.0.4 -> 10.45.202.100 (UDP) @ 5478900K on Port 29024 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 29024 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 29024 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -u -B 10.45.0.4 -c 10.45.202.100 -p 29024 -u -b 5478900K -t 120" > output.log 2>&1 &

# --- Flow 6: 10.45.100.101 -> 10.45.100.102 (BGP) @ 170K on Port 27049 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 27049 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 27049 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.100.102 -p 27049 -b 170K -t 120" > output.log 2>&1 &

# --- Flow 7: 10.45.100.101 -> 10.45.100.102 (TCP) @ 66K on Port 25628 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25628 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 25628 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.100.102 -p 25628 -b 66K -t 120" > output.log 2>&1 &

# --- Flow 8: 10.45.110.81 -> 10.45.65.200 (SCTP) @ 848K on Port 20144 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 20144 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 20144 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.65.200 -p 20144 -b 848K -t 120" > output.log 2>&1 &

# --- Flow 9: 10.45.202.100 -> 104.16.174.226 (TCP) @ 162K on Port 59265 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 59265 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 59265 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 104.16.174.226 -p 59265 -b 162K -t 120" > output.log 2>&1 &

# --- Flow 10: 10.45.202.100 -> 104.17.148.22 (HTTP) @ 1421K on Port 17717 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 17717 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 17717 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 104.17.148.22 -p 17717 -b 1421K -t 120" > output.log 2>&1 &

# --- Flow 11: 10.45.202.100 -> 104.17.148.22 (TCP) @ 588K on Port 55348 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 55348 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 55348 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 104.17.148.22 -p 55348 -b 588K -t 120" > output.log 2>&1 &

# --- Flow 12: 10.45.202.100 -> 134.224.0.55 (TCP) @ 324K on Port 59540 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 59540 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 59540 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 134.224.0.55 -p 59540 -b 324K -t 120" > output.log 2>&1 &

# --- Flow 13: 10.45.202.100 -> 134.224.0.55 (TLSv1.2) @ 85K on Port 46741 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 46741 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 46741 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 134.224.0.55 -p 46741 -b 85K -t 120" > output.log 2>&1 &

# --- Flow 14: 10.45.202.100 -> 159.124.52.153 (DTLSv1.2) @ 1339932K on Port 16697 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 16697 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 16697 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 159.124.52.153 -p 16697 -b 1339932K -t 120" > output.log 2>&1 &

# --- Flow 15: 10.45.202.100 -> 159.124.52.153 (STUN) @ 14352K on Port 49698 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 49698 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 49698 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 159.124.52.153 -p 49698 -b 14352K -t 120" > output.log 2>&1 &

# --- Flow 16: 10.45.202.100 -> 159.124.52.153 (TCP) @ 75536K on Port 38651 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 38651 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 38651 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 159.124.52.153 -p 38651 -b 75536K -t 120" > output.log 2>&1 &

# --- Flow 17: 10.45.202.100 -> 159.124.52.153 (TLSv1.2) @ 833906K on Port 13082 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 13082 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 13082 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 159.124.52.153 -p 13082 -b 833906K -t 120" > output.log 2>&1 &

# --- Flow 18: 10.45.202.100 -> 162.159.61.3 (QUIC) @ 16380K on Port 12952 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 12952 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 12952 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 162.159.61.3 -p 12952 -b 16380K -t 120" > output.log 2>&1 &

# --- Flow 19: 10.45.202.100 -> 170.114.52.2 (TCP) @ 445K on Port 17140 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 17140 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 17140 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 170.114.52.2 -p 17140 -b 445K -t 120" > output.log 2>&1 &

# --- Flow 20: 10.45.202.100 -> 170.114.52.38 (TCP) @ 445K on Port 25328 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25328 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 25328 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 170.114.52.38 -p 25328 -b 445K -t 120" > output.log 2>&1 &

# --- Flow 21: 10.45.202.100 -> 172.64.41.3 (SSL) @ 55K on Port 26247 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 26247 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 26247 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 172.64.41.3 -p 26247 -b 55K -t 120" > output.log 2>&1 &

# --- Flow 22: 10.45.202.100 -> 172.64.41.3 (TCP) @ 66K on Port 44118 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 44118 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 44118 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 172.64.41.3 -p 44118 -b 66K -t 120" > output.log 2>&1 &

# --- Flow 23: 10.45.202.100 -> 2.22.248.154 (QUIC) @ 18694K on Port 50453 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 50453 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 50453 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 2.22.248.154 -p 50453 -b 18694K -t 120" > output.log 2>&1 &

# --- Flow 24: 10.45.202.100 -> 20.74.32.47 (TCP) @ 174K on Port 12739 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 12739 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 12739 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 20.74.32.47 -p 12739 -b 174K -t 120" > output.log 2>&1 &

# --- Flow 25: 10.45.202.100 -> 23.103.240.192 (SSL) @ 55K on Port 47781 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 47781 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 47781 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 23.103.240.192 -p 47781 -b 55K -t 120" > output.log 2>&1 &

# --- Flow 26: 10.45.202.100 -> 23.103.240.192 (TCP) @ 66K on Port 24031 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 24031 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 24031 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 23.103.240.192 -p 24031 -b 66K -t 120" > output.log 2>&1 &

# --- Flow 27: 10.45.202.100 -> 23.216.150.179 (UDP) @ 2129K on Port 57925 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 57925 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 57925 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -u -B 10.45.0.4 -c 23.216.150.179 -p 57925 -u -b 2129K -t 120" > output.log 2>&1 &

# --- Flow 28: 10.45.202.100 -> 4.208.165.247 (TCP) @ 216K on Port 53590 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 53590 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 53590 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 4.208.165.247 -p 53590 -b 216K -t 120" > output.log 2>&1 &

# --- Flow 29: 10.45.202.100 -> 40.127.240.158 (SSL) @ 590K on Port 56962 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 56962 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 56962 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 40.127.240.158 -p 56962 -b 590K -t 120" > output.log 2>&1 &

# --- Flow 30: 10.45.202.100 -> 40.127.240.158 (TCP) @ 9804K on Port 46713 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 46713 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 46713 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 40.127.240.158 -p 46713 -b 9804K -t 120" > output.log 2>&1 &

# --- Flow 31: 10.45.202.100 -> 40.127.240.158 (TLSv1.2) @ 4734K on Port 38493 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 38493 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 38493 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 40.127.240.158 -p 38493 -b 4734K -t 120" > output.log 2>&1 &

# --- Flow 32: 10.45.202.100 -> 52.102.112.196 (SSL) @ 55K on Port 25446 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25446 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 25446 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.102.112.196 -p 25446 -b 55K -t 120" > output.log 2>&1 &

# --- Flow 33: 10.45.202.100 -> 52.102.112.196 (TCP) @ 66K on Port 40439 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 40439 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 40439 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.102.112.196 -p 40439 -b 66K -t 120" > output.log 2>&1 &

# --- Flow 34: 10.45.202.100 -> 52.102.115.224 (SSL) @ 55K on Port 49618 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 49618 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 49618 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.102.115.224 -p 49618 -b 55K -t 120" > output.log 2>&1 &

# --- Flow 35: 10.45.202.100 -> 52.102.115.224 (TCP) @ 66K on Port 29231 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 29231 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 29231 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.102.115.224 -p 29231 -b 66K -t 120" > output.log 2>&1 &

# --- Flow 36: 10.45.202.100 -> 52.110.16.208 (SSL) @ 55K on Port 11425 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 11425 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 11425 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.110.16.208 -p 11425 -b 55K -t 120" > output.log 2>&1 &

# --- Flow 37: 10.45.202.100 -> 52.110.16.208 (TCP) @ 66K on Port 21463 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 21463 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 21463 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.110.16.208 -p 21463 -b 66K -t 120" > output.log 2>&1 &

# --- Flow 38: 10.45.202.100 -> 52.112.126.35 (TCP) @ 270K on Port 56753 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 56753 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 56753 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.112.126.35 -p 56753 -b 270K -t 120" > output.log 2>&1 &

# --- Flow 39: 10.45.202.100 -> 52.112.126.35 (TLSv1.2) @ 2428K on Port 38696 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 38696 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 38696 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.112.126.35 -p 38696 -b 2428K -t 120" > output.log 2>&1 &

# --- Flow 40: 10.45.202.100 -> 52.123.144.199 (TCP) @ 108K on Port 33298 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 33298 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 33298 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.123.144.199 -p 33298 -b 108K -t 120" > output.log 2>&1 &

# --- Flow 41: 10.45.202.100 -> 52.123.144.199 (TLSv1.2) @ 426K on Port 29210 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 29210 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 29210 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 52.123.144.199 -p 29210 -b 426K -t 120" > output.log 2>&1 &

# --- Flow 42: 10.45.202.100 -> 72.145.163.205 (SSL) @ 2973K on Port 21189 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 21189 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 21189 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 72.145.163.205 -p 21189 -b 2973K -t 120" > output.log 2>&1 &

# --- Flow 43: 10.45.202.100 -> 72.145.163.205 (TCP) @ 980K on Port 25110 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25110 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 25110 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 72.145.163.205 -p 25110 -b 980K -t 120" > output.log 2>&1 &

# --- Flow 44: 10.45.202.100 -> 72.145.163.205 (TLSv1.2) @ 795K on Port 33059 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 33059 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 33059 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 72.145.163.205 -p 33059 -b 795K -t 120" > output.log 2>&1 &

# --- Flow 45: 10.45.202.100 -> 74.125.250.129 (STUN) @ 816K on Port 17698 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 17698 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 17698 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 74.125.250.129 -p 17698 -b 816K -t 120" > output.log 2>&1 &

../../cmd_container.sh upf_cld "tcpdump -i ogstun -G 30 -W 1 -w capture.pcap" 
docker cp upf_cld:/open5gs/capture.pcap /tmp/temp.pcap
