#!/bin/bash
# Script generated by process_flows_v2.py to simulate aggregated network traffic using iperf3.
# Mapping file used: ip_mapping_example.csv
# NOTE: The throughput is used as the bandwidth limit (-b) and is assumed to be in Kbps (K).

# Clean up any previous iperf3 server daemons before starting
../../cmd_container.sh internet_server "pkill iperf3" 
# --- Flow 1: host-A-core -> 224.0.0.102 (UDP) @ 13440K on Port 52905 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 52905 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 224.0.0.102 -p 52905 -u -b 13440K -t 10" > output.log 2>&1 &

# --- Flow 2: host-A-core -> 224.0.0.18 (VRRP) @ 19840K on Port 18296 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 18296 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 224.0.0.18 -p 18296 -b 19840K -t 10" > output.log 2>&1 &

# --- Flow 3: host-D-server -> 192.168.0.201 (GTP) @ 2237568K on Port 12639 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 12639 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.201 -p 12639 -b 2237568K -t 10" > output.log 2>&1 &

# --- Flow 4: 192.168.0.201 -> 192.168.0.201 (SCTP) @ 12704K on Port 59598 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 59598 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.201 -p 59598 -b 12704K -t 10" > output.log 2>&1 &

# --- Flow 5: 192.168.0.201 -> 192.168.0.201 (SCTP) @ 10976K on Port 29024 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 29024 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.201 -p 29024 -b 10976K -t 10" > output.log 2>&1 &

# --- Flow 6: 192.168.0.201 -> 10.252.249.3 (GTP) @ 2260608K on Port 27049 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 27049 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.252.249.3 -p 27049 -b 2260608K -t 10" > output.log 2>&1 &

# --- Flow 7: host-E-client -> 224.0.1.1 (UDP) @ 3680K on Port 25628 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25628 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 224.0.1.1 -p 25628 -u -b 3680K -t 10" > output.log 2>&1 &

# --- Flow 8: host-E-client -> 255.255.255.255 (UDP) @ 19600K on Port 20144 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 20144 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 255.255.255.255 -p 20144 -u -b 19600K -t 10" > output.log 2>&1 &

