#!/bin/bash
# Script generated by process_flows_v4.py to simulate aggregated network traffic using iperf3.
# Mapping file used: ip_mapping_cnit.csv
# NOTE: The throughput is used as the bandwidth limit (-b) and is assumed to be in Kbps (K).

# Clean up any previous iperf3 server daemons before starting
../../cmd_container.sh internet_server "pkill iperf3" 
../../cmd_container.sh ue1 "pkill iperf3" 
# Run tcpdump on all interfaces (120 sec.)
sudo tcpdump -i s3-internet -s 0 -G 120 -w all_traffic_internet.pcap &

# --- Flow 1: 172.30.252.3 -> 10.45.0.4 (SSH) @ 91K on Port 52905 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 52905 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 52905 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 52905 -b 91K -t 120" > output.log 2>&1 &

# --- Flow 2: 172.30.252.3 -> 10.45.0.4 (SSHv2) @ 1462K on Port 18296 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 18296 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 18296 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 18296 -b 1462K -t 120" > output.log 2>&1 &

# --- Flow 3: 172.30.252.3 -> 10.45.0.4 (TCP) @ 206K on Port 12639 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 12639 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 12639 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 12639 -b 206K -t 120" > output.log 2>&1 &

# --- Flow 4: 172.30.252.3 -> 10.45.0.4 (SSH) @ 91K on Port 59598 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 59598 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 59598 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 59598 -b 91K -t 120" > output.log 2>&1 &

# --- Flow 5: 172.30.252.3 -> 10.45.0.4 (SSHv2) @ 1462K on Port 29024 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 29024 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 29024 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 29024 -b 1462K -t 120" > output.log 2>&1 &

# --- Flow 6: 172.30.252.3 -> 10.45.0.4 (TCP) @ 338K on Port 27049 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 27049 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 27049 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 27049 -b 338K -t 120" > output.log 2>&1 &

# --- Flow 7: 172.30.252.3 -> 192.168.0.200 (SSH) @ 15374K on Port 25628 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25628 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 25628 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.200 -p 25628 -b 15374K -t 120" > output.log 2>&1 &

# --- Flow 8: 172.30.252.3 -> 192.168.0.200 (TCP) @ 1122K on Port 20144 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 20144 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 20144 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.200 -p 20144 -b 1122K -t 120" > output.log 2>&1 &

# --- Flow 9: 172.30.252.3 -> 10.45.0.4 (SSH) @ 91K on Port 59265 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 59265 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 59265 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 59265 -b 91K -t 120" > output.log 2>&1 &

# --- Flow 10: 172.30.252.3 -> 10.45.0.4 (SSHv2) @ 1462K on Port 17717 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 17717 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 17717 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 17717 -b 1462K -t 120" > output.log 2>&1 &

# --- Flow 11: 172.30.252.3 -> 10.45.0.4 (TCP) @ 206K on Port 55348 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 55348 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 55348 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 55348 -b 206K -t 120" > output.log 2>&1 &

# --- Flow 12: 172.30.252.3 -> 10.45.0.4 (SSH) @ 91K on Port 59540 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 59540 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 59540 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 59540 -b 91K -t 120" > output.log 2>&1 &

# --- Flow 13: 172.30.252.3 -> 10.45.0.4 (SSHv2) @ 1462K on Port 46741 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 46741 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 46741 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 46741 -b 1462K -t 120" > output.log 2>&1 &

# --- Flow 14: 172.30.252.3 -> 10.45.0.4 (TCP) @ 338K on Port 16697 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 16697 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 16697 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 16697 -b 338K -t 120" > output.log 2>&1 &

# --- Flow 15: 10.45.0.4 -> 192.168.0.200 (HTTP) @ 8925K on Port 49698 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 49698 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 49698 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.200 -p 49698 -b 8925K -t 120" > output.log 2>&1 &

# --- Flow 16: 10.45.0.4 -> 192.168.0.200 (TCP) @ 10880K on Port 38651 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 38651 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 38651 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.200 -p 38651 -b 10880K -t 120" > output.log 2>&1 &

# --- Flow 17: 10.45.0.4 -> 192.168.0.200 (HTTP) @ 9541K on Port 13082 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 13082 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 13082 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.200 -p 13082 -b 9541K -t 120" > output.log 2>&1 &

# --- Flow 18: 10.45.0.4 -> 192.168.0.200 (TCP) @ 10880K on Port 12952 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 12952 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 12952 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.0.200 -p 12952 -b 10880K -t 120" > output.log 2>&1 &

# --- Flow 19: 192.168.0.200 -> 192.168.130.18 (TCP) @ 994166K on Port 17140 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 17140 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 17140 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.130.18 -p 17140 -b 994166K -t 120" > output.log 2>&1 &

# --- Flow 20: 192.168.0.200 -> 192.168.130.18 (TLSv1.2) @ 3415972K on Port 25328 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25328 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 25328 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.130.18 -p 25328 -b 3415972K -t 120" > output.log 2>&1 &

# --- Flow 21: 192.168.0.200 -> 192.168.130.18 (UDP) @ 196750K on Port 26247 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 26247 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 26247 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.130.18 -p 26247 -u -b 196750K -t 120" > output.log 2>&1 &

# --- Flow 22: 192.168.0.200 -> 192.168.130.48 (HTTP) @ 128261K on Port 44118 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 44118 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 44118 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.130.48 -p 44118 -b 128261K -t 120" > output.log 2>&1 &

# --- Flow 23: 192.168.0.200 -> 192.168.130.48 (TCP) @ 6270K on Port 50453 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 50453 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 50453 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.130.48 -p 50453 -b 6270K -t 120" > output.log 2>&1 &

# --- Flow 24: 192.168.0.200 -> 10.45.0.4 (HTTP) @ 9418K on Port 12739 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 12739 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 12739 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 12739 -b 9418K -t 120" > output.log 2>&1 &

# --- Flow 25: 192.168.0.200 -> 10.45.0.4 (TCP) @ 10880K on Port 47781 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 47781 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 47781 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 47781 -b 10880K -t 120" > output.log 2>&1 &

# --- Flow 26: 192.168.0.200 -> 10.45.0.4 (HTTP) @ 9613K on Port 24031 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 24031 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 24031 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 24031 -b 9613K -t 120" > output.log 2>&1 &

# --- Flow 27: 192.168.0.200 -> 10.45.0.4 (TCP) @ 10880K on Port 57925 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 57925 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 57925 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 57925 -b 10880K -t 120" > output.log 2>&1 &

# --- Flow 28: 192.168.0.200 -> 192.168.130.9 (NFS) @ 94579014K on Port 53590 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 53590 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 53590 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.130.9 -p 53590 -b 94579014K -t 120" > output.log 2>&1 &

# --- Flow 29: 192.168.0.200 -> 192.168.130.9 (TCP) @ 12592228K on Port 56962 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 56962 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 56962 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.130.9 -p 56962 -b 12592228K -t 120" > output.log 2>&1 &

# --- Flow 30: 192.168.0.200 -> 10.45.0.4 (HTTP) @ 9106K on Port 46713 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 46713 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 46713 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 46713 -b 9106K -t 120" > output.log 2>&1 &

# --- Flow 31: 192.168.0.200 -> 10.45.0.4 (TCP) @ 10880K on Port 38493 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 38493 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 38493 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 10.45.0.4 -p 38493 -b 10880K -t 120" > output.log 2>&1 &

# --- Flow 32: 192.168.0.200 -> 192.168.255.25 (DNS) @ 1868K on Port 25446 ---
../../cmd_container.sh internet_server "timeout 2m iperf3 -s -B 192.168.0.201 -p 25446 -D" > output.log 2>&1 &
../../cmd_container.sh dns_s "timeout 2m iperf3 -s -B 192.168.0.200 -p 25446 -D" > output.log 2>&1 &
../../cmd_container.sh ue1 "iperf3 -B 10.45.0.4 -c 192.168.255.25 -p 25446 -b 1868K -t 120" > output.log 2>&1 &

